material_kerf: # Values from https://cutlasercut.com/drawing-resources/expert-tips/laser-kerf/
  MDF:
    3: 0.16
  plywood:
    1: 0.11
    3: 0.2
  acrylic:
    3: 0.18
    6: 0.21
    12: 0.30

edge_material:
  thickness: 3.0
  material: 'MDF'
  default_sizes:
    height: 600
    width: 600
  specific_boards:

spacer_material:
  thickness: 1.0
  material: 'plywood'
  default_sizes:
    height: 600
    width: 600
  specific_boards:
